name: Update Issue Template Version

on:
  push:
    paths:
      - 'package.json'  # Trigger the workflow only when package.json is changed

jobs:
  update-version-in-template:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Extract version
      id: pkg_version
      run: echo "::set-output name=version::$(cat package.json | jq -r '.version')"

    - name: Update issue template
      run: |
        sed -i 's/ex\. 2\.0\.10/${{ steps.pkg_version.outputs.version }}/g' .github/ISSUE_TEMPLATE/bug_report.yml

    - name: Commit and push if changed
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add .github/ISSUE_TEMPLATE/bug_report.yml
        git commit -m "Update version in issue template to ${{ steps.pkg_version.outputs.version }}" || exit 0
        git push
